import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.mainContent}>
      <Head>
        <title>Meme Guesser</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.HeaderCon}>
        <h1>Meme Guesser</h1>
      </header>

      <main className={styles.GuesserCon}>
        <section className={styles.syno}>
          <p className={styles.syno__item}>First item</p>
          <p className={styles.syno__item}>Second item</p>
          <p className={styles.syno__item}>Third item</p>
        </section>

        <form className={styles.guessingForm}>
          <input
            type="text"
            maxLength={1}
            className={styles.guessingForm__text_field}
          />
          <input
            type="text"
            maxLength={1}
            className={styles.guessingForm__text_field}
          />
          <input
            type="text"
            maxLength={1}
            className={styles.guessingForm__text_field}
          />
          <input
            type="text"
            maxLength={1}
            className={styles.guessingForm__text_field}
          />
        </form>
      </main>
    </div>
  );
};

export default Home;
