name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thanks for submitting the issue! We'll be taking a look at it shortly."
        pr-message: "Welcome aboard to the clueless word game and thanks for submitting the PR! It will get looked at shortly"
